# COMA parameters

# Detailed explanation for each hyper parameter can be found in ray/rllib/agents/a3c/a2c.py

algo_args:
  use_gae: True
  lambda: 1.0
  vf_loss_coeff: 1.0
  batch_episode:  10
  batch_mode: "complete_episodes"
  lr: 0.0005
  entropy_coeff: 0.01
