env: football

env_args:
  map_name: "academy_pass_and_shoot_with_keeper" # other available maps can be found in football.py
  logdir: ""
  render: False
  dump_frequency: 0

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
fixed_batch_timesteps: 4000 # optional, all scenario will use this batch size, only valid for on-policy algorithms
