env: metadrive

env_args:
  map_name: "Bottleneck" # ParkingLot | Intersection | Roundabout | Tollgate | Bottleneck
  start_seed: 0
  num_agents: 5
  crash_done: True

mask_flag: False
global_state_flag: False
opp_action_in_cc: False