env: rware

env_args:
  n_agents: 2 # 2-20
  map_size: "tiny" # "tiny", "small", "medium", "large"
  difficulty: "medium" # "easy", "medium", "hard"
  column_height: 1
  max_inactivity_steps: null
  max_steps: 500
  fast_obs: True
  msg_bits: 0
  sensor_range: 1

mask_flag: False
global_state_flag: False
opp_action_in_cc: True
