# VDN parameters

algo_args:
  batch_episode:  32
  lr: 0.0005
  rollout_fragment_length: 1
  buffer_size: 5000
  target_network_update_freq: 100
  final_epsilon: 0.05
  epsilon_timesteps: 50000
  optimizer: "rmsprop" # "adam"
  reward_standardize: True